name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Bash
      run: ./build-all.sh kernel             
           ./build-all.sh initramfs    
           ./build-all.sh rootfs       
           ./build-all.sh qemu        
           ./build-all.sh termux

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      env:
       PODROID_RELEASE_STORE_FILE: ${{ secrets.PODROID_RELEASE_STORE_FILE }}
       PODROID_RELEASE_STORE_PASSWORD: ${{ secrets.PODROID_RELEASE_STORE_PASSWORD }}
       PODROID_RELEASE_KEY_ALIAS: ${{ secrets.PODROID_RELEASE_KEY_ALIAS }}
       PODROID_RELEASE_KEY_PASSWORD: ${{ secrets.PODROID_RELEASE_KEY_PASSWORD }}
      run: ./gradlew assembleRelease
